const tags = [
  {
    id: "1",
    selected: false,
    color: "#CF202E",
    showPalette: false,
    name: "review",
    tagged_items: 18,
    assigned_to: "Marko Markovic",
    expundge_date: "Nov 22, 2020",
    options: null,
    date_created: "Nov 22, 2016",
    created_by: "Marko Antic"
  },
  {
    id: "2",
    selected: false,
    color: "#67C8C7",
    showPalette: false,
    name: "assigned",
    tagged_items: 43,
    assigned_to: null,
    expundge_date: "indefinitely",
    options: "notifies",
    date_created: "Sep 10, 2018",
    created_by: "Marko Antic"
  },
  {
    id: "3",
    selected: false,
    color: "#CF202E",
    showPalette: false,
    name: "something",
    tagged_items: 23,
    assigned_to: "Aleksandar Nikolic",
    expundge_date: null,
    options: "2 Rules",
    date_created: "Jan 03, 2019",
    created_by: "Marko Antic"
  },
  {
    id: "4",
    selected: false,
    color: "#C1D42F",
    showPalette: false,
    name: "legal",
    tagged_items: null,
    assigned_to: null,
    expundge_date: null,
    options: null,
    date_created: "Feb 18, 2017",
    created_by: "Marko Antic"
  },
  {
    id: "5",
    selected: false,
    color: "#000000",
    showPalette: false,
    name: "custom tag",
    tagged_items: null,
    assigned_to: null,
    expundge_date: null,
    options: "notifies",
    date_created: "Feb 22, 2017",
    created_by: "Marko Antic"
  },
  {
    id: "6",
    selected: false,
    color: "#CF202E",
    showPalette: false,
    name: "review",
    tagged_items: 18,
    assigned_to: "Marko Markovic",
    expundge_date: "Nov 22, 2020",
    options: null,
    date_created: "Nov 22, 2016",
    created_by: "Marko Antic"
  },
  {
    id: "7",
    selected: false,
    color: "#67C8C7",
    showPalette: false,
    name: "assigned",
    tagged_items: 43,
    assigned_to: null,
    expundge_date: "indefinitely",
    options: "notifies",
    date_created: "Sep 10, 2018",
    created_by: "Marko Antic"
  },
  {
    id: "8",
    selected: false,
    color: "#CF202E",
    showPalette: false,
    name: "something",
    tagged_items: 23,
    assigned_to: "Aleksandar Nikolic",
    expundge_date: null,
    options: "2 Rules",
    date_created: "Jan 03, 2019",
    created_by: "Marko Antic"
  },
  {
    id: "9",
    selected: false,
    color: "#C1D42F",
    showPalette: false,
    name: "legal",
    tagged_items: null,
    assigned_to: null,
    expundge_date: null,
    options: null,
    date_created: "Feb 18, 2017",
    created_by: "Marko Antic"
  },
  {
    id: "10",
    selected: false,
    color: "#000000",
    showPalette: false,
    name: "custom tag",
    tagged_items: null,
    assigned_to: null,
    expundge_date: null,
    options: "notifies",
    date_created: "Feb 22, 2017",
    created_by: "Marko Antic"
  },
  {
    id: "11",
    selected: false,
    color: "#CF202E",
    showPalette: false,
    name: "review",
    tagged_items: 18,
    assigned_to: "Marko Markovic",
    expundge_date: "Nov 22, 2020",
    options: null,
    date_created: "Nov 22, 2016",
    created_by: "Marko Antic"
  },
  {
    id: "12",
    selected: false,
    color: "#67C8C7",
    showPalette: false,
    name: "assigned",
    tagged_items: 43,
    assigned_to: null,
    expundge_date: "indefinitely",
    options: "notifies",
    date_created: "Sep 10, 2018",
    created_by: "Marko Antic"
  },
  {
    id: "13",
    selected: false,
    color: "#CF202E",
    showPalette: false,
    name: "something",
    tagged_items: 23,
    assigned_to: "Aleksandar Nikolic",
    expundge_date: null,
    options: "2 Rules",
    date_created: "Jan 03, 2019",
    created_by: "Marko Antic"
  },
  {
    id: "14",
    selected: false,
    color: "#C1D42F",
    showPalette: false,
    name: "legal",
    tagged_items: null,
    assigned_to: null,
    expundge_date: null,
    options: null,
    date_created: "Feb 18, 2017",
    created_by: "Marko Antic"
  },
  {
    id: "15",
    selected: false,
    color: "#000000",
    showPalette: false,
    name: "custom tag",
    tagged_items: null,
    assigned_to: null,
    expundge_date: null,
    options: "notifies",
    date_created: "Feb 22, 2017",
    created_by: "Marko Antic"
  },
  {
    id: "16",
    selected: false,
    color: "#CF202E",
    showPalette: false,
    name: "review",
    tagged_items: 18,
    assigned_to: "Marko Markovic",
    expundge_date: "Nov 22, 2020",
    options: null,
    date_created: "Nov 22, 2016",
    created_by: "Marko Antic"
  },
  {
    id: "17",
    selected: false,
    color: "#67C8C7",
    showPalette: false,
    name: "assigned",
    tagged_items: 43,
    assigned_to: null,
    expundge_date: "indefinitely",
    options: "notifies",
    date_created: "Sep 10, 2018",
    created_by: "Marko Antic"
  },
  {
    id: "18",
    selected: false,
    color: "#CF202E",
    showPalette: false,
    name: "something",
    tagged_items: 23,
    assigned_to: "Aleksandar Nikolic",
    expundge_date: null,
    options: "2 Rules",
    date_created: "Jan 03, 2019",
    created_by: "Marko Antic"
  },
  {
    id: "19",
    selected: false,
    color: "#C1D42F",
    showPalette: false,
    name: "legal",
    tagged_items: null,
    assigned_to: null,
    expundge_date: null,
    options: null,
    date_created: "Feb 18, 2017",
    created_by: "Marko Antic"
  },
  {
    id: "20",
    selected: false,
    color: "#000000",
    showPalette: false,
    name: "custom tag",
    tagged_items: null,
    assigned_to: null,
    expundge_date: null,
    options: "notifies",
    date_created: "Feb 22, 2017",
    created_by: "Marko Antic"
  },
  {
    id: "21",
    selected: false,
    color: "#CF202E",
    showPalette: false,
    name: "review",
    tagged_items: 18,
    assigned_to: "Marko Markovic",
    expundge_date: "Nov 22, 2020",
    options: null,
    date_created: "Nov 22, 2016",
    created_by: "Marko Antic"
  },
  {
    id: "22",
    selected: false,
    color: "#67C8C7",
    showPalette: false,
    name: "assigned",
    tagged_items: 43,
    assigned_to: null,
    expundge_date: "indefinitely",
    options: "notifies",
    date_created: "Sep 10, 2018",
    created_by: "Marko Antic"
  },
  {
    id: "23",
    selected: false,
    color: "#CF202E",
    showPalette: false,
    name: "something",
    tagged_items: 23,
    assigned_to: "Aleksandar Nikolic",
    expundge_date: null,
    options: "2 Rules",
    date_created: "Jan 03, 2019",
    created_by: "Marko Antic"
  },
  {
    id: "24",
    selected: false,
    color: "#C1D42F",
    showPalette: false,
    name: "legal",
    tagged_items: null,
    assigned_to: null,
    expundge_date: null,
    options: null,
    date_created: "Feb 18, 2017",
    created_by: "Marko Antic"
  },
  {
    id: "25",
    selected: false,
    color: "#000000",
    showPalette: false,
    name: "custom tag",
    tagged_items: null,
    assigned_to: null,
    expundge_date: null,
    options: "notifies",
    date_created: "Feb 22, 2017",
    created_by: "Marko Antic"
  }
];

export default tags;
